// <auto-generated />
using System;
using DormitoryManagementSystem.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DormitoryManagementSystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260105110635_SyncUsersIsLivingInDormitory")]
    partial class SyncUsersIsLivingInDormitory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DormitoryManagementSystem.Models.AdminMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Завтра відключення води з 9:00 до 18:00.",
                            CreatedAt = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Title = "Екстрене повідомлення"
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.Dormitory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dormitories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Гуртожиток №1"
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Факультет бізнесу та сфери обслуговування"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Факультет гірничої справи, природокористування та будівництва"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Факультет інформаційно-комп'ютерних технологій"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Факультет комп'ютерно-інтегрованих технологій, мехатроніки і робототехніки"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Факультет національної безпеки, права та міжнародних відносин"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Факультет педагогічних технологій та освіти впродовж життя"
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DormitoryId")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlacesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DormitoryId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Тестова кімната",
                            DormitoryId = 1,
                            Floor = 1,
                            Name = "11/3",
                            PlacesCount = 2
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.RoomPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoomId = 1
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.ShowerReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.HasIndex("UserId", "SlotId")
                        .IsUnique();

                    b.ToTable("ShowerReservations");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.ShowerSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxReservations")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("ShowerSlots");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Course")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FormOfEducation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLivingInDormitory")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomPlaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("RoomPlaceId")
                        .IsUnique()
                        .HasFilter("[RoomPlaceId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@ztu.edu.ua",
                            FullName = "Тестовий Адмін",
                            IsAdmin = true,
                            IsLivingInDormitory = false,
                            PasswordHash = "admin123",
                            PhoneNumber = "+380991112233"
                        },
                        new
                        {
                            Id = 2,
                            Course = 2,
                            Email = "resident@student.ztu.edu.ua",
                            FacultyId = 3,
                            FormOfEducation = "Денна",
                            FullName = "Тестова Резидентка",
                            Gender = "Жіноча",
                            Group = "ІПЗ-23-0",
                            IsAdmin = false,
                            IsLivingInDormitory = true,
                            PasswordHash = "resident123",
                            PhoneNumber = "+380991112244",
                            RoomPlaceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Course = 1,
                            Email = "resident2@student.ztu.edu.ua",
                            FacultyId = 3,
                            FormOfEducation = "Денна",
                            FullName = "Тестова Резидентка2",
                            Gender = "Жіноча",
                            Group = "ІПЗ-24-0",
                            IsAdmin = false,
                            IsLivingInDormitory = true,
                            PasswordHash = "resident2123",
                            PhoneNumber = "+380966879654",
                            RoomPlaceId = 2
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.ContactMessage", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Models.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.Room", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Models.Dormitory", "Dormitory")
                        .WithMany("Rooms")
                        .HasForeignKey("DormitoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.RoomPlace", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Models.Room", "Room")
                        .WithMany("Places")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.ShowerReservation", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Models.ShowerSlot", "Slot")
                        .WithMany("Reservations")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DormitoryManagementSystem.Models.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.UserInfo", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Models.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId");

                    b.HasOne("DormitoryManagementSystem.Models.RoomPlace", "RoomPlace")
                        .WithOne("Student")
                        .HasForeignKey("DormitoryManagementSystem.Models.UserInfo", "RoomPlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Faculty");

                    b.Navigation("RoomPlace");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.Dormitory", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.Room", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.RoomPlace", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Models.ShowerSlot", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
